### PR TITLE
face recognition from openCV

### PR DESCRIPTION
**Pull request by Dextroxe**
Here this time i added more examples for this project
using the openCV for images detection then using haarcascade for saving the dataset then compare that dataset to the predicted image

### CODE REVIEW

**Comment by darshML** [comment]
I DONT SEE ANY CODE FILES, ONLY SUB MODULES FOLDER

**Comment by Dextroxe** [comment]
Wait wht but I added the 3 coded files which are in python

**Comment by Dextroxe** [comment]
Wait does the repo only work with 1 language,
Bcz that shouldn't happen

**Comment by Dextroxe** [comment]
Ig I'll create other pr with different branch name 🥲

May be it will work...

**Pull request closed without merging**
